-- ============================================================================
-- Suraksha 00_setup.sql : warehouse, database, schemas, roles.  Idempotent.
-- Run as ACCOUNTADMIN (or a role with CREATE ROLE / CREATE WAREHOUSE / CREATE DATABASE).
--   snow sql -f sql/00_setup.sql
-- ============================================================================
USE ROLE ACCOUNTADMIN;

-- ---- compute: XS, aggressive auto-suspend to keep hackathon cost near zero
CREATE WAREHOUSE IF NOT EXISTS SURAKSHA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Suraksha demo warehouse';

-- ---- database + schemas
CREATE DATABASE IF NOT EXISTS SURAKSHA COMMENT = 'Suraksha trade-finance duplicate-financing detection';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.CORE        COMMENT = 'workflow state, audit log, policy, rules, docs stage';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.REGISTRY    COMMENT = 'synthetic company registry (MCA21 stand-in)';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.CONSORTIUM  COMMENT = 'shared hash-only consortium ledger';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.BANK_A      COMMENT = 'Bank A private data (simulated)';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.BANK_B      COMMENT = 'Bank B private data (simulated)';
CREATE SCHEMA IF NOT EXISTS SURAKSHA.BANK_C      COMMENT = 'Bank C private data (simulated)';

-- ---- roles
CREATE ROLE IF NOT EXISTS SURAKSHA_ADMIN   COMMENT = 'owns all Suraksha objects';
CREATE ROLE IF NOT EXISTS SURAKSHA_APP     COMMENT = 'application role used by SnowflakeStore / Streamlit';
CREATE ROLE IF NOT EXISTS SURAKSHA_AUDITOR COMMENT = 'read-only on audit log + verification view';
CREATE ROLE IF NOT EXISTS BANK_A_ROLE      COMMENT = 'Bank A: may pledge only BANK_A rows to consortium';
CREATE ROLE IF NOT EXISTS BANK_B_ROLE      COMMENT = 'Bank B: may pledge only BANK_B rows to consortium';
CREATE ROLE IF NOT EXISTS BANK_C_ROLE      COMMENT = 'Bank C: may pledge only BANK_C rows to consortium';

-- hierarchy: ACCOUNTADMIN -> SURAKSHA_ADMIN; app role inherits the three bank roles
-- (single-account simulation. In production each bank has its own account and role.)
GRANT ROLE SURAKSHA_ADMIN   TO ROLE ACCOUNTADMIN;
GRANT ROLE BANK_A_ROLE      TO ROLE SURAKSHA_APP;
GRANT ROLE BANK_B_ROLE      TO ROLE SURAKSHA_APP;
GRANT ROLE BANK_C_ROLE      TO ROLE SURAKSHA_APP;
GRANT ROLE SURAKSHA_APP     TO ROLE SURAKSHA_ADMIN;
GRANT ROLE SURAKSHA_AUDITOR TO ROLE SURAKSHA_ADMIN;

-- ---- ownership / usage
GRANT OWNERSHIP ON DATABASE SURAKSHA TO ROLE SURAKSHA_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE SURAKSHA TO ROLE SURAKSHA_ADMIN COPY CURRENT GRANTS;
GRANT USAGE, OPERATE ON WAREHOUSE SURAKSHA_WH TO ROLE SURAKSHA_ADMIN;
GRANT USAGE ON WAREHOUSE SURAKSHA_WH TO ROLE SURAKSHA_APP;
GRANT USAGE ON WAREHOUSE SURAKSHA_WH TO ROLE SURAKSHA_AUDITOR;

GRANT USAGE ON DATABASE SURAKSHA TO ROLE SURAKSHA_APP;
GRANT USAGE ON DATABASE SURAKSHA TO ROLE SURAKSHA_AUDITOR;
GRANT USAGE ON DATABASE SURAKSHA TO ROLE BANK_A_ROLE;
GRANT USAGE ON DATABASE SURAKSHA TO ROLE BANK_B_ROLE;
GRANT USAGE ON DATABASE SURAKSHA TO ROLE BANK_C_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.CORE       TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.CORE       TO ROLE SURAKSHA_AUDITOR;
GRANT USAGE ON SCHEMA SURAKSHA.REGISTRY   TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.CONSORTIUM TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.CONSORTIUM TO ROLE BANK_A_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.CONSORTIUM TO ROLE BANK_B_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.CONSORTIUM TO ROLE BANK_C_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_A TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_B TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_C TO ROLE SURAKSHA_APP;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_A TO ROLE BANK_A_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_B TO ROLE BANK_B_ROLE;
GRANT USAGE ON SCHEMA SURAKSHA.BANK_C TO ROLE BANK_C_ROLE;

-- Cortex AI functions need this database role (PUBLIC has it by default; explicit for clarity)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SURAKSHA_APP;

-- Give your user the roles, e.g.:
--   GRANT ROLE SURAKSHA_ADMIN TO USER <your_user>;
--   GRANT ROLE SURAKSHA_APP   TO USER <your_user>;
